# -*- coding: utf-8 -*-
"""Sistema_de_auditoria

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAQTJ9C7ZKcCaW0ICcw9u9SQXy4S0S-W

# Conheça o Colab

Sistema de aditoria de recursos
"""

import time

# Decorator de auditoria
def auditor(func):
    def wrapper(*args, **kwargs):
        print("=== AUDITORIA DE ORÇAMENTO ===")
        print(f"Função: {func.__name__}")
        print(f"Args (departamentos ignorados): {args}")
        print(f"Kwargs (parâmetros financeiros): {kwargs}")
        inicio = time.time()

        resultado = func(*args, **kwargs)

        fim = time.time()
        print(f"Tempo total de execução: {fim - inicio:.4f} segundos")
        print("=== FIM DA AUDITORIA ===\n")
        return resultado
    return wrapper

# Estrutura de dados simulando a empresa
empresa = {
    "Matriz": {
        "TI": {
            "Infraestrutura": 100000,
            "Desenvolvimento": 200000
        },
        "RH": {
            "Recrutamento": 50000,
            "Treinamento": 75000
        },
        "Financeiro": {
            "Contabilidade": 120000,
            "Planejamento": 90000
        }
    }
}

# Função recursiva para cálculo de orçamento
@auditor
def calcular_orcamento(*departamentos_ignorados, **kwargs):
    def navegar(dados):
        total = 0
        for chave, valor in dados.items():
            if chave in departamentos_ignorados:
                print(f"Ignorando departamento: {chave}")
                continue
            if isinstance(valor, dict):
                total += navegar(valor)
            else:
                total += valor
        return total

    total = navegar(empresa)

    # Conversão de moeda se houver taxa de câmbio
    taxa = kwargs.get("taxa_cambio", 1)
    moeda = kwargs.get("moeda_destino", "USD")
    total_convertido = total * taxa

    print(f"Orçamento total convertido para {moeda}: {total_convertido}")
    return total_convertido

# Exemplo de execução
if __name__ == "__main__":
    calcular_orcamento("RH", moeda_destino="BRL", taxa_cambio=5.20)