# -*- coding: utf-8 -*-
"""Programaçao. COMPUTADORES_UNICID

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Otg-SbKkjtIUy3bgjbCjXc5Qv_ao-Toh

# AULA 01
 SLIDE NO BLACKBOARD

# AULA 02
"""

print("Olá mundo!")

1# a indentaçao de codigo se refere aos espaços no inicio de uma linha
if 5 >2:
   print("cinco e maior que dois!")
else:
  print("Cinco nao e maior que dois!")

#Passo 1: Variaveis
  num1 = 8
  num2 = 12
  num3 = 10

  # Passo 2: Calculo
  soma = num1 + num2 + num3
  media = soma / 3

  # Passo 3: Verificar se a media e maior que 10
  resultado = "Aprovdo" if media >= 10 else "Reprovado"

  # Passo 4: imprimir os Resultados
  print(":"*40)
  print("Numero 01:", num1)
  print("Numero 02:", num2)
  print("Numero 03:", num3)
  print("Soma:", soma)
  print("Media:", media)
  print("Resultado:", resultado)
  print(":"*40)

num1 = int(input("Numero 01: "))
num2 = int(input("NUmero 02: "))
num3 = int(input("Numero 03: "))

media = (num1 + num2 + num3) / 3

if media >= 10:
  print("Aprovado")
else:
  print("Reprovado")

  print("-"*40)
  print(f"Numero 1: {num1}")
  print(f"Numero 2: {num2}")
  print(f"Numero 3: {num3}")
  print(f"Media: {media:.2f}")
  print("-"*40)

# Calculo de IMC

 # Entrada
 peso = float(input("Peso:"))
 altura = float(input("Altura:"))

 # Processamento
 imc = peso / (altura * altura)

 # Saida
 print("-"*40)
 print(f"Peso: {peso}")
 print(f"Altura: {altura}")
 print(f"IMC: {imc:.2f}")
 if imc < 18.5:
   print("Abaixo do peso")
 elif imc < 25:
   print("Peso normal")
 elif imc < 30:
   print("Sobrepeso")
 elif imc < 35:
   print("Sobrepeso")
 elif imc < 40:
  print("Sobrepeso")
 elif imc >= 40:
  print("Sobrepeso")
 else:
  print("valor invalido")
 print("=+"*20)

celsius = float(input("Temperatura em Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print(f"Teperatura em Fahrenheit: {fahrenheit:.2f}")

x = 10
 y = 8.9
 z = "Henrique"
 w = True
 a =
 b =
 c =
 d =

# Valores diferentes
 x, y, z = "Laranja", "Banana", "Maça"
 print(x) # Laranja
 print(y) # Banana
 print(z) # Maça

# 1. Configuração Global
LIMITE_SEGURANCA = 10000.00
print(f"Limite de Segurança inicial: R$ {LIMITE_SEGURANCA:,.2f}")

# 2. Entrada de Dados e Casting
# Certifica que o programa aceite números decimais e substitui ',' por '.' para conversão correta.
vendas = []
for i in range(1, 4):
    while True:
        try:
            valor_venda = input(f"Digite o valor da venda {i} do dia (ex: 1234.56): ").replace(',', '.')
            vendas.append(float(valor_venda))
            break
        except ValueError:
            print("Entrada inválida. Por favor, digite um número.")

venda1, venda2, venda3 = vendas[0], vendas[1], vendas[2]

print(f"Venda 1: R$ {venda1:,.2f}")
print(f"Venda 2: R$ {venda2:,.2f}")
print(f"Venda 3: R$ {venda3:,.2f}")

# 3. Processamento Interno (Função analisar_vendas) e Lógica de Investigação
def analisar_vendas(v1, v2, v3):
    global LIMITE_SEGURANCA # Permite a alteração da variável global

    print("\n--- Análise de Vendas ---")

    # Calcula a Média Simples
    media = (v1 + v2 + v3) / 3
    print(f"Média das vendas: R$ {media:,.2f}")

    # Lógica de Investigação
    if media > LIMITE_SEGURANCA:
        print("ALERTA: SISTEMA EM QUARENTENA!")
        # Exemplo de como o gerente poderia ajustar o limite se uma venda for legítima
        # Isso aqui é um exemplo e pode ser ajustado com mais lógica ou interação do usuário
        if any(v > LIMITE_SEGURANCA * 1.5 for v in [v1, v2, v3]): # Se alguma venda for 50% acima do limite
            print("Sugestão: Vendas individuais muito altas. Considere ajustar o LIMITE_SEGURANCA se forem legítimas.")
            # Neste ponto, um gerente poderia intervir para, por exemplo, aumentar o LIMITE_SEGURANCA
            # Para este exemplo, não faremos uma alteração automática sem input do usuário.

    discrepancia_detectada = False
    for venda in [v1, v2, v3]:
        if venda >= media * 5: # Se uma venda for 5x maior que a média
            print(f"ALERTA: Venda de R$ {venda:,.2f} é 5x maior que a média. Sugere-se REVISÃO MANUAL!")
            discrepancia_detectada = True

    if not discrepancia_detectada and media <= LIMITE_SEGURANCA:
        print("Nenhuma anomalia grave detectada. Vendas dentro dos parâmetros.")

    return media

# Chamada da função
media_vendas = analisar_vendas(venda1, venda2, venda3)


# 4. Apresentação: Exibir tipo de dado de cada variável
print("\n--- Verificação de Tipos de Dados ---")
print(f"Tipo de LIMITE_SEGURANCA: {type(LIMITE_SEGURANCA)}")
print(f"Tipo de venda1: {type(venda1)}")
print(f"Tipo de venda2: {type(venda2)}")
print(f"Tipo de venda3: {type(venda3)}")
print(f"Tipo da média das vendas: {type(media_vendas)}")

print(f"\nO LIMITE_SEGURANCA atual é: R$ {LIMITE_SEGURANCA:,.2f}") # Exibe o limite atual, caso tenha sido 'considerado' para ajuste no futuro

"""Investigação e Descoberta




O que é Discrepância de Dados

1.  Porque a média soma tudo: um valor muito alto ou muito baixo puxa o resultado para ele, mesmo sendo só um número diferente dos outros.


O conceito de Normalização

2. por que dependendo se o numero e baixo ou alto pode alterar a media virando uma medida pouco confiável

Lógica de negocio

3. o valor máximo de erro aceitável em uma auditoria. Se o erro ficar dentro dessa margem, não é considerado importante. Se passar, vira problema

O teste (100, 200 e 5000) gerou uma média de R$ 1.766,66, o que não acionou a "quarentena" porque o valor ainda estava abaixo do limite de R$ 10 mil.
O sistema seguiu as regras, mas mostrou uma falha de segurança: a venda de 5.000 era muito suspeita, mas "passou batido" porque o alerta só dispara se o valor for 5x maior que a média.

Para o sistema ficar realmente esperto e seguro como um banco, a sugestão é baixar esse gatilho de 5x para 2.5x, tornando o filtro mais sensível a valores estranhos

Usar global em sistemas bancários é um risco real porque permite que qualquer erro ou ataque altere o limite de segurança, abrindo brechas para fraudes invisíveis. O padrão profissional é encapsular essa regra em um local trancado e externo, garantindo que o sistema apenas consulte o valor sem poder modificá-lo sem rastro de auditoria
"""



"""O erro mais chato é o UnboundLocalError, que rola quando você tenta mexer no limite dentro da função e esquece de avisar que é a variável lá de fora usando o global. A gente percebe que algo deu ruim na intuição mesmo, antes de ler o erro, só de ver uma cor estranha no editor ou sentir que o código "travou" num cálculo que deveria ser simples. Na nossa cabeça, o computador deveria saber que estamos falando daquele limite lá do topo, mas na real ele se perde achando que você está criando uma regra nova do zero e tenta usar um valor que ainda nem existe"""